<?php

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('Room')->insert(array(
      #Centenial 1
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '107'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '109'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '113'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '114'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '115'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '116'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '117'],
      ['BuildingID' => 1, 'FloorID' => 1, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '119'],

      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '202'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '203'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '204'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '205'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '206'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '207'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '208'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 2, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '209'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '210'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '212'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '213'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '214'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '215'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '216'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '217'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '219'],
      ['BuildingID' => 1, 'FloorID' => 2, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '220'],

      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '302'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '303'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '304'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '305'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '306'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '307'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 2, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '308'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '309'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '310'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '312'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '313'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '314'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '315'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '316'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '317'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '319'],
      ['BuildingID' => 1, 'FloorID' => 3, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '320'],

      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '402'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '403'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '404'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '405'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '406'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '407'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 2, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '408'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '409'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '410'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '412'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '413'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '414'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '415'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '416'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '417'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '419'],
      ['BuildingID' => 1, 'FloorID' => 4, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '420'],
      #Davis 2
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '131'],
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '133'],
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '134'],
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '136'],
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '138'],
      ['BuildingID' => 2, 'FloorID' => 5, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '139'],

      ['BuildingID' => 2, 'FloorID' => 6, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '231'],
      ['BuildingID' => 2, 'FloorID' => 6, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '234'],
      ['BuildingID' => 2, 'FloorID' => 6, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '236'],
      ['BuildingID' => 2, 'FloorID' => 6, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '238'],
      ['BuildingID' => 2, 'FloorID' => 6, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '239'],

      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '331'],
      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '332'],
      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '334'],
      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '336'],
      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '338'],
      ['BuildingID' => 2, 'FloorID' => 7, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '339'],

      ['BuildingID' => 2, 'FloorID' => 8, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '431'],
      ['BuildingID' => 2, 'FloorID' => 8, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '432'],
      ['BuildingID' => 2, 'FloorID' => 8, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '434'],
      ['BuildingID' => 2, 'FloorID' => 8, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '436'],
      ['BuildingID' => 2, 'FloorID' => 8, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '439'],
      #Jenks East 3
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '101A'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '101B'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '105'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '107'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '109'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '111'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '113'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '115'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '116'],
      ['BuildingID' => 3, 'FloorID' => 9, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '118'],

      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '203'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '205'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '206'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '207'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '208'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '209'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '211'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '213'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '215'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '216'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '217'],
      ['BuildingID' => 3, 'FloorID' => 10, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '218'],

      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '303'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '305'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '306'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '307'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '308'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '309'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '311'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '313'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '315'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '316'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '317'],
      ['BuildingID' => 3, 'FloorID' => 11, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '318'],

      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '403'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '405'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '407A'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '407B'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '408A'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '408B'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '411A'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '411B'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '413'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '315'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '416A'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '416B'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '417A'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '417B'],
      ['BuildingID' => 3, 'FloorID' => 12, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '418'],

      #Jenks West 4
      ['BuildingID' => 4, 'FloorID' => 13, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '127'],
      ['BuildingID' => 4, 'FloorID' => 13, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '129A'],
      ['BuildingID' => 4, 'FloorID' => 13, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '129A'],

      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '221A'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '221B'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '223A'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '223B'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '227'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '229A'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '229B'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '231A'],
      ['BuildingID' => 4, 'FloorID' => 14, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '231B'],

      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '321A'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '321B'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '323A'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '323B'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '327'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '329A'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '329B'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '331A'],
      ['BuildingID' => 4, 'FloorID' => 15, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '331B'],

      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '321A'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '321B'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '323A'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '323B'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '327'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '329A'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '329B'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '331A'],
      ['BuildingID' => 4, 'FloorID' => 16, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '331B'],
      
      #Memorial 5
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '101'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '102'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '104'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '106'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '108'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '110'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '116'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '118'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '120'],
      ['BuildingID' => 5, 'FloorID' => 17, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '122'],

      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '201'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '202'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '204'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '206'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '208'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '209'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '210'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '211'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '212'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '213'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '216'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '218'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '220'],
      ['BuildingID' => 5, 'FloorID' => 18, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '222'],

      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '301'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '302'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '304'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '306'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '308'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '309'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '310'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '311'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '312'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '313'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '316'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '318'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '320'],
      ['BuildingID' => 5, 'FloorID' => 19, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '322'],

      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '401'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '402'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '404'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '406'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '408'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '409'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '410'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '411'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '412'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '415'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '416'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '418'],
      ['BuildingID' => 5, 'FloorID' => 20, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '422'],

      #Watkins East 6
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '003'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '005'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '006'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '007'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '009'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '011'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '012'],
      ['BuildingID' => 6, 'FloorID' => 21, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '014'],

      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '104'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '106'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '107'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '108'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '110'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '111'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '112'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '113'],
      ['BuildingID' => 6, 'FloorID' => 22, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '114'],

      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '201A'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '201B'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '202'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '203'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '204'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '205'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '207'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '209'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '210'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '211'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '212'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '213'],
      ['BuildingID' => 6, 'FloorID' => 23, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '214'],

      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '301A'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '301B'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '302'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '303'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '304'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '305'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '307'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '309'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '310'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '311'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '312'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '313'],
      ['BuildingID' => 6, 'FloorID' => 24, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '314'],

      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '401A'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '401B'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '402'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '403'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '404'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '405'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '407'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '409'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '410'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '411'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '412'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '413'],
      ['BuildingID' => 6, 'FloorID' => 25, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '414'],

      #Watkins West 7
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '049'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '051'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '053'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '056'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '058'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '059'],
      ['BuildingID' => 7, 'FloorID' => 26, 'Capacity' => 4, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '061'],

      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '151'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '152'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '153'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '154'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '156'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '158'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '159'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '160'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '161'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '162'],
      ['BuildingID' => 7, 'FloorID' => 27, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '163'],

      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '251'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '252A'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '252B'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '253'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '254'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '255'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '256'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '258'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '260'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '261'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '262'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '263'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '264'],
      ['BuildingID' => 7, 'FloorID' => 28, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '265'],

      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '351'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '352A'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '352B'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '353'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '354'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '355'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '356'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '358'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '360'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '361'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '362'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '363'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '364'],
      ['BuildingID' => 7, 'FloorID' => 29, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '365'],

      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '451'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '452A'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '452B'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '453'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '454'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '455'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '456'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '458'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '460'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '461'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '462'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '463'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '464'],
      ['BuildingID' => 7, 'FloorID' => 30, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '465'],

      #Wilkinson 8
      ['BuildingID' => 8, 'FloorID' => 31, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '001'],
      ['BuildingID' => 8, 'FloorID' => 31, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '002'],
      ['BuildingID' => 8, 'FloorID' => 31, 'Capacity' => 0, 'AmountTaken' => 0, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '003'],

      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '101'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '102'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '103'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '104'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '105'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '107'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '111'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '113'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '114'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '115'],
      ['BuildingID' => 8, 'FloorID' => 32, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '116'],

      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '201'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '202'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '203'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '204'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '205'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '207'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '209'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '210'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '211'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '213'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '214'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '215'],
      ['BuildingID' => 8, 'FloorID' => 33, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '216'],

      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '301'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 3, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '302'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 2, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '303'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '305'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 1, 'AmountTaken' => 1, 'IsAvailable' => 0, 'YearOfResidenceID' => 1, 'RoomNumber' => '307'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '309'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '310'],
      ['BuildingID' => 8, 'FloorID' => 34, 'Capacity' => 1, 'AmountTaken' => 0, 'IsAvailable' => 1, 'YearOfResidenceID' => 1, 'RoomNumber' => '311']
      
    )
		);
    }
}
